### ISSUE TITLE
Нет заряда приемника и датчика 7.18

### ISSUE THREAD

**Issue by pharaoh2ths** [Zentelechia/bat-mobile#1]
Не пишет заряд при подключении приемника, также после опроса датчика и при его подключении. Пустота, работало на предыдущей. Пробовал разные ССО. Пробовал переподключение к заявке.

**Comment by Zentelechia** [comment]
исправлено а 5.6.7.19 - сохраненные при первом запуске программы настройки содержали регулярные выражения для определения уровня заряда устройств для старых комплектов
