### ISSUE TITLE
Кривое отображение экрана "Укажите причину срабатывания".

### ISSUE THREAD

**Issue by pharaoh2ths** [Zentelechia/bat-mobile#3]
Где "введите комментарий" - введите с заглавно буквы + прямоугольник для введения не полный (отсутсвует верхняя граница). Сделайте фотографию - прямоугольник с фото уходит за экран.

**Comment by Zentelechia** [comment]
Готово в версии 19

**Comment by Zentelechia** [comment]
.

**Comment by Zentelechia** [comment]
исправлено в 5.6.7.19
